version: '2'
services:
  nginx:
    ports:
        - "80:80"
    build: ./nginx
    volumes:
      - /home/lee/mysb/docker-nginx-django-angular2/nginx/angular2:/usr/share/nginx/angular2
    networks: 
      - front-tier

  web:
    build: ./django_server
    expose: 
        - "8000"
    networks: 
      - front-tier
      - back-tier
    command: /usr/local/bin/gunicorn django_server.wsgi:application -w 2 -b :8000

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - back-tier 
    #command: "./docker-entrypoint.sh"django_server:

#angular2 直接由nginx處理，須將angular2 copy to nginx directory.
volumes: 
  redisdata:

networks:
  front-tier:
  back-tier: